version: '1.0'

services:
  frontend:
    container_name: starbucks-frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - .:/app/node_modules
    ports:
      - 3000:3000

      